runtime: custom
runtime_config:
    python_version: 2
env: flex
entrypoint: python main.py
api_version: 1
threadsafe: true
handlers:
- url: /.*
  script: main.my_app
readiness_check:
  app_start_timeout_sec: 500
# libraries:
# - name: ssl
#   version: latest
# - name: numpy
#   version: "1.6.1"